// mobile/lib/destinations.ts
// Curated Discover content. Bundled fallback + day-1 data; the `destinations`
// Supabase table overrides it when non-empty (see lib/discover.ts).
export const THEMES = ["nature", "adventure", "culture", "food", "wildlife", "city", "beach"] as const;
export type Theme = (typeof THEMES)[number];

export const TAGS = ["popular", "trending", "underRadar"] as const;
export type Tag = (typeof TAGS)[number];

export const CONTINENTS = ["africa", "asia", "europe", "north-america", "oceania", "south-america"] as const;
export type Continent = (typeof CONTINENTS)[number];

export interface Destination {
  id: string;             // slug, e.g. "kyoto-japan"
  name: string;
  country: string;
  countryCode: string;    // ISO-3166 alpha-2, uppercase — drives emoji flag
  continent: Continent;
  themes: Theme[];        // 1–3
  tags: Tag[];            // 0–2
  blurb: string;          // 1–2 sentences
  highlights: string[];   // 3–5
  imageUrl: string;       // https, verified by scripts/check-image-urls.mjs
  lat: number;
  lng: number;
}

export const DESTINATIONS: Destination[] = [
  {
    id: "kyoto-japan",
    name: "Kyoto",
    country: "Japan",
    countryCode: "JP",
    continent: "asia",
    themes: ["culture", "food"],
    tags: ["popular"],
    blurb: "Japan's old imperial capital: thousands of temples, lantern-lit lanes, and kaiseki dining beneath the maples.",
    highlights: ["Fushimi Inari torii gates", "Arashiyama bamboo grove", "Gion at dusk", "Kinkaku-ji"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Kinkaku-ji%20in%20November%202016%20-02.jpg?width=900",
    lat: 35.0116,
    lng: 135.7681,
  },
  {
    id: "faroe-islands-denmark",
    name: "Faroe Islands",
    country: "Denmark",
    countryCode: "FO",
    continent: "europe",
    themes: ["nature", "adventure"],
    tags: ["underRadar"],
    blurb: "Eighteen storm-carved islands where waterfalls pour straight into the Atlantic and sheep outnumber people.",
    highlights: ["Múlafossur waterfall", "Sørvágsvatn cliff lake", "Puffin colonies on Mykines"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Mulafossur%20Waterfall.jpg?width=900",
    lat: 62.0,
    lng: -6.79,
  },
  {
    id: "oaxaca-mexico",
    name: "Oaxaca",
    country: "Mexico",
    countryCode: "MX",
    continent: "north-america",
    themes: ["food", "culture"],
    tags: ["trending"],
    blurb: "Mexico's food capital — smoky moles, mezcal palenques, and Zapotec ruins above a baroque colonial core.",
    highlights: ["Mercado 20 de Noviembre", "Monte Albán", "Mezcal tastings", "Hierve el Agua"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Church%20of%20Santo%20Domingo%20in%20Oaxaca.jpg?width=900",
    lat: 17.0732,
    lng: -96.7266,
  },
  {
    id: "paris-france",
    name: "Paris",
    country: "France",
    countryCode: "FR",
    continent: "europe",
    themes: ["city", "culture"],
    tags: ["popular"],
    blurb: "The City of Light pairs Haussmann boulevards and world-class museums with unmatched café culture and pastry.",
    highlights: ["Louvre", "Eiffel Tower at night", "Montmartre", "Seine river walk"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Tour%20Eiffel%20Wikimedia%20Commons.jpg?width=900",
    lat: 48.8566,
    lng: 2.3522,
  },
  {
    id: "rome-italy",
    name: "Rome",
    country: "Italy",
    countryCode: "IT",
    continent: "europe",
    themes: ["culture", "city"],
    tags: ["popular"],
    blurb: "Three thousand years of history stacked in one city — ancient ruins, Renaissance piazzas, and unbeatable pasta.",
    highlights: ["Colosseum", "Roman Forum", "Trevi Fountain", "Vatican Museums", "Trastevere at night"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Colosseum%20in%20Rome%2C%20Italy%20-%20April%202007.jpg?width=900",
    lat: 41.9028,
    lng: 12.4964,
  },
  {
    id: "santorini-greece",
    name: "Santorini",
    country: "Greece",
    countryCode: "GR",
    continent: "europe",
    themes: ["beach", "culture"],
    tags: ["popular"],
    blurb: "Whitewashed cliffside villages overlook a volcanic caldera, with some of the best sunsets in the Aegean.",
    highlights: ["Oia sunset", "Fira caldera walk", "Red Beach", "wine tasting"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Oia%20Santorini%20sunset.jpg?width=900",
    lat: 36.3932,
    lng: 25.4615,
  },
  {
    id: "barcelona-spain",
    name: "Barcelona",
    country: "Spain",
    countryCode: "ES",
    continent: "europe",
    themes: ["city", "culture"],
    tags: ["trending"],
    blurb: "Gaudí's surreal architecture meets Mediterranean beaches, tapas bars, and late-night energy.",
    highlights: ["Sagrada Família", "Park Güell", "La Rambla", "Gothic Quarter", "Barceloneta beach"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Sagrada%20Familia%20March%202015-19bw.jpg?width=900",
    lat: 41.3851,
    lng: 2.1734,
  },
  {
    id: "lake-bled-slovenia",
    name: "Lake Bled",
    country: "Slovenia",
    countryCode: "SI",
    continent: "europe",
    themes: ["nature", "adventure"],
    tags: ["underRadar"],
    blurb: "An island church floats on a glacial lake beneath a clifftop castle, ringed by the Julian Alps.",
    highlights: ["Bled Island church", "Bled Castle", "rowing a pletna boat", "Vintgar Gorge"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Panorama%20Bled%2001.jpg?width=900",
    lat: 46.3683,
    lng: 14.1146,
  },
  {
    id: "berat-albania",
    name: "Berat",
    country: "Albania",
    countryCode: "AL",
    continent: "europe",
    themes: ["culture", "city"],
    tags: ["underRadar"],
    blurb: "The \"City of a Thousand Windows\" stacks Ottoman houses up a hillside beneath a working castle.",
    highlights: ["Berat Castle", "Mangalem quarter", "Gorica Bridge", "Osum River"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Berat%20-%20Gorica%20Bridge%20%28by%20Pudelek%29.JPG?width=900",
    lat: 40.7058,
    lng: 19.9522,
  },
  {
    id: "tbilisi-georgia",
    name: "Tbilisi",
    country: "Georgia",
    countryCode: "GE",
    continent: "europe",
    themes: ["food", "culture"],
    tags: ["underRadar"],
    blurb: "Sulfur bathhouses, wine cellars, and a maze of balconied Old Town streets in the cradle of winemaking.",
    highlights: ["Old Town", "sulfur baths", "Narikala Fortress", "khachapuri and natural wine"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Tbilisi%2C%20Old%20town%2C%20Georgia.jpg?width=900",
    lat: 41.7151,
    lng: 44.8271,
  },
  {
    id: "algarve-portugal",
    name: "Algarve",
    country: "Portugal",
    countryCode: "PT",
    continent: "europe",
    themes: ["beach", "nature"],
    tags: ["trending"],
    blurb: "Golden sea cliffs, hidden grottoes, and quiet coves along Portugal's sun-soaked southern coast.",
    highlights: ["Benagil Cave", "Praia da Marinha", "Lagos old town", "Ponta da Piedade"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Portugal%20-%20Algarve%20-%20Coast%20at%20sunset%20%2825683034071%29.jpg?width=900",
    lat: 37.0179,
    lng: -7.9304,
  },
  {
    id: "lofoten-norway",
    name: "Lofoten Islands",
    country: "Norway",
    countryCode: "NO",
    continent: "europe",
    themes: ["nature", "adventure"],
    tags: ["underRadar"],
    blurb: "Jagged granite peaks rise straight out of the Arctic sea beside fishing villages and midnight sun.",
    highlights: ["Reine village", "Kvalvika Beach", "hiking Reinebringen", "Nusfjord"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Sildpollnes%20Church%20and%20Higravstindan%20in%20morning%2C%20Austv%C3%A5g%C3%B8ya%2C%20Lofoten%2C%20Norway%2C%202015%20April.jpg?width=900",
    lat: 68.15,
    lng: 13.6,
  },
  {
    id: "prague-czechia",
    name: "Prague",
    country: "Czechia",
    countryCode: "CZ",
    continent: "europe",
    themes: ["culture", "city"],
    tags: ["popular"],
    blurb: "A fairy-tale skyline of spires and a medieval castle overlooks the Vltava and its cobbled Old Town.",
    highlights: ["Charles Bridge", "Prague Castle", "Old Town Square astronomical clock", "beer halls"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/North%20view%20of%20Charles%20Bridge%20from%20M%C3%A1nes%C5%AFv%20most%2C%20Prague%2020160808%201.jpg?width=900",
    lat: 50.0755,
    lng: 14.4378,
  },
  {
    id: "amalfi-coast-italy",
    name: "Amalfi Coast",
    country: "Italy",
    countryCode: "IT",
    continent: "europe",
    themes: ["beach", "nature"],
    tags: ["popular"],
    blurb: "Pastel villages cling to cliffs above the Tyrrhenian Sea along one of Europe's most scenic coastal drives.",
    highlights: ["Positano", "Path of the Gods hike", "Ravello gardens", "limoncello tasting"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Positano%20%28Italy%29%2004.jpg?width=900",
    lat: 40.6333,
    lng: 14.6029,
  },
  {
    id: "iceland-golden-circle",
    name: "Iceland",
    country: "Iceland",
    countryCode: "IS",
    continent: "europe",
    themes: ["nature", "adventure"],
    tags: ["popular"],
    blurb: "Glaciers, geysers, and waterfalls collide with volcanic black-sand coastline under the northern lights.",
    highlights: ["Gullfoss waterfall", "Blue Lagoon", "Skógafoss", "Diamond Beach", "Geysir"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Gullfoss%2C%20Iceland%2C%2020230501%200949%203809.jpg?width=900",
    lat: 64.1466,
    lng: -21.9426,
  },
  {
    id: "zermatt-switzerland",
    name: "Zermatt",
    country: "Switzerland",
    countryCode: "CH",
    continent: "europe",
    themes: ["adventure", "nature"],
    tags: ["trending"],
    blurb: "A car-free alpine village sits in the shadow of the Matterhorn, ringed by glaciers and ski slopes.",
    highlights: ["Matterhorn Glacier Paradise", "Gornergrat railway", "Riffelsee reflection", "alpine hiking"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Zermatt%20and%20Matterhorn.jpg?width=900",
    lat: 46.0207,
    lng: 7.7491,
  },
  {
    id: "bangkok-thailand",
    name: "Bangkok",
    country: "Thailand",
    countryCode: "TH",
    continent: "asia",
    themes: ["city", "food"],
    tags: ["popular"],
    blurb: "Gilded temples and canal-side markets sit minutes from rooftop bars and some of Asia's best street food.",
    highlights: ["Wat Arun", "Grand Palace", "floating markets", "street-food alleys", "Chatuchak Market"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Templo%20Wat%20Arun%2C%20Bangkok%2C%20Tailandia%2C%202013-08-22%2C%20DD%2030.jpg?width=900",
    lat: 13.7563,
    lng: 100.5018,
  },
  {
    id: "bali-indonesia",
    name: "Bali",
    country: "Indonesia",
    countryCode: "ID",
    continent: "asia",
    themes: ["beach", "culture"],
    tags: ["popular"],
    blurb: "Emerald rice terraces, Hindu temples, and surf beaches make Bali Southeast Asia's most iconic island escape.",
    highlights: ["Tegallalang rice terraces", "Uluwatu Temple", "Ubud", "Seminyak beaches"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Tegallalang%20Rice%20Terraces%20Bali%201.jpg?width=900",
    lat: -8.3405,
    lng: 115.092,
  },
  {
    id: "bhutan",
    name: "Bhutan",
    country: "Bhutan",
    countryCode: "BT",
    continent: "asia",
    themes: ["culture", "nature"],
    tags: ["underRadar"],
    blurb: "A Himalayan kingdom that measures Gross National Happiness, with cliffside monasteries and pristine valleys.",
    highlights: ["Tiger's Nest Monastery", "Punakha Dzong", "Paro Valley", "prayer-flag mountain passes"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Paro%20Taktsang%2C%20Bhutan%20%28edited%29.jpg?width=900",
    lat: 27.4287,
    lng: 89.6296,
  },
  {
    id: "luang-prabang-laos",
    name: "Luang Prabang",
    country: "Laos",
    countryCode: "LA",
    continent: "asia",
    themes: ["culture", "food"],
    tags: ["underRadar"],
    blurb: "Saffron-robed monks collect alms each dawn in this UNESCO river town of gilded temples and French cafés.",
    highlights: ["Alms-giving ceremony", "Kuang Si Falls", "Mount Phousi", "night market"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Panoramic%20view%20of%20Mount%20Phou%20Si%20seen%20from%20Wat%20Chomphet%20in%20Luang%20Prabang%20Laos.jpg?width=900",
    lat: 19.8856,
    lng: 102.1347,
  },
  {
    id: "halong-bay-vietnam",
    name: "Ha Long Bay",
    country: "Vietnam",
    countryCode: "VN",
    continent: "asia",
    themes: ["nature", "adventure"],
    tags: ["trending"],
    blurb: "Thousands of limestone karsts rise from emerald water, best explored by overnight junk boat and kayak.",
    highlights: ["Karst-studded cruise", "kayaking hidden lagoons", "Sung Sot Cave", "floating villages"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Halong%20Bay%20in%20Vietnam.jpg?width=900",
    lat: 20.9101,
    lng: 107.1839,
  },
  {
    id: "sri-lanka",
    name: "Sri Lanka",
    country: "Sri Lanka",
    countryCode: "LK",
    continent: "asia",
    themes: ["wildlife", "culture"],
    tags: ["underRadar"],
    blurb: "Ancient rock fortresses, tea-covered hills, and leopard-filled national parks packed into one island.",
    highlights: ["Sigiriya rock fortress", "Yala leopard safari", "Ella train ride", "Temple of the Tooth"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Sigiriya%2002.jpg?width=900",
    lat: 6.8667,
    lng: 81.0466,
  },
  {
    id: "nepal-himalaya",
    name: "Nepal",
    country: "Nepal",
    countryCode: "NP",
    continent: "asia",
    themes: ["adventure", "culture"],
    tags: ["trending"],
    blurb: "The Himalaya's highest peaks tower over Kathmandu's temple squares and legendary trekking trails.",
    highlights: ["Everest Base Camp trek", "Kathmandu Durbar Square", "Annapurna Circuit", "Pokhara lakeside"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Everest%2C%20Himalayas.jpg?width=900",
    lat: 27.7172,
    lng: 85.324,
  },
  {
    id: "petra-jordan",
    name: "Petra",
    country: "Jordan",
    countryCode: "JO",
    continent: "asia",
    themes: ["culture", "adventure"],
    tags: ["popular"],
    blurb: "A rose-red city carved into desert cliffs by the Nabataeans, reached through a narrow winding canyon.",
    highlights: ["The Treasury", "the Siq canyon walk", "Monastery hike", "Wadi Rum desert camp nearby"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/The%20Treasury%2C%20Petra%2C%20Jordan1.jpg?width=900",
    lat: 30.3285,
    lng: 35.4444,
  },
  {
    id: "maldives",
    name: "Maldives",
    country: "Maldives",
    countryCode: "MV",
    continent: "asia",
    themes: ["beach", "nature"],
    tags: ["popular"],
    blurb: "Coral atolls ring turquoise lagoons and overwater bungalows in the Indian Ocean's ultimate barefoot escape.",
    highlights: ["Overwater villas", "house-reef snorkeling", "bioluminescent plankton beaches", "sandbank picnics"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/MaldivesBungalows.jpg?width=900",
    lat: 4.1755,
    lng: 73.5093,
  },
  {
    id: "new-york-city-usa",
    name: "New York City",
    country: "United States",
    countryCode: "US",
    continent: "north-america",
    themes: ["city", "culture"],
    tags: ["popular"],
    blurb: "Skyscraper canyons, world-class museums, and a borough for every craving make NYC the archetypal metropolis.",
    highlights: ["Central Park", "Times Square", "Brooklyn Bridge", "MoMA", "Broadway"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Manhattan%20from%20Weehawken%2C%20NJ.jpg?width=900",
    lat: 40.7128,
    lng: -74.006,
  },
  {
    id: "banff-canada",
    name: "Banff National Park",
    country: "Canada",
    countryCode: "CA",
    continent: "north-america",
    themes: ["nature", "adventure"],
    tags: ["popular"],
    blurb: "Turquoise glacial lakes sit beneath jagged Rockies peaks in Canada's oldest national park.",
    highlights: ["Lake Louise", "Moraine Lake", "Icefields Parkway", "Banff Gondola"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/1%20lake%20louise%20pano%202019.jpg?width=900",
    lat: 51.1784,
    lng: -115.5708,
  },
  {
    id: "monteverde-costa-rica",
    name: "Monteverde",
    country: "Costa Rica",
    countryCode: "CR",
    continent: "north-america",
    themes: ["wildlife", "nature"],
    tags: ["trending"],
    blurb: "Suspended bridges thread through a misty cloud forest alive with quetzals, sloths, and hummingbirds.",
    highlights: ["Cloud forest canopy walk", "zip-lining", "hummingbird gardens", "night wildlife walk"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Monteverde%20Cloud%20Forest%20%2828367816878%29.jpg?width=900",
    lat: 10.3009,
    lng: -84.8007,
  },
  {
    id: "havana-cuba",
    name: "Havana",
    country: "Cuba",
    countryCode: "CU",
    continent: "north-america",
    themes: ["culture", "city"],
    tags: ["underRadar"],
    blurb: "Crumbling pastel façades, vintage American cars, and live salon music fill this time-capsule capital.",
    highlights: ["Malecón seawall", "Old Havana plazas", "classic car tour", "live salsa clubs"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/National-Capitol-and-classic-cars-in-Havana-Cuba-225-031-061A.jpg?width=900",
    lat: 23.1136,
    lng: -82.3666,
  },
  {
    id: "tulum-mexico",
    name: "Tulum",
    country: "Mexico",
    countryCode: "MX",
    continent: "north-america",
    themes: ["beach", "culture"],
    tags: ["trending"],
    blurb: "Mayan ruins overlook white-sand Caribbean beaches, with cenotes and jungle just inland.",
    highlights: ["Tulum ruins over the sea", "cenote swimming", "Sian Ka'an biosphere", "beach clubs"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Tulum%20-%2001.jpg?width=900",
    lat: 20.2114,
    lng: -87.4654,
  },
  {
    id: "patagonia-argentina",
    name: "Patagonia",
    country: "Argentina",
    countryCode: "AR",
    continent: "south-america",
    themes: ["nature", "adventure"],
    tags: ["popular"],
    blurb: "Granite spires and wind-scoured steppe make this the end of the earth for hikers and glacier watchers.",
    highlights: ["Fitz Roy trek", "Perito Moreno Glacier", "Torres del Paine views", "El Chaltén trails"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Fitz%20Roy%201.jpg?width=900",
    lat: -49.3315,
    lng: -72.988,
  },
  {
    id: "galapagos-ecuador",
    name: "Galápagos Islands",
    country: "Ecuador",
    countryCode: "EC",
    continent: "south-america",
    themes: ["wildlife", "nature"],
    tags: ["popular"],
    blurb: "Darwin's living laboratory, where giant tortoises, marine iguanas, and blue-footed boobies show no fear of people.",
    highlights: ["Giant tortoise reserves", "snorkeling with sea lions", "blue-footed booby colonies", "volcanic landscapes"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Gal%C3%A1pagos%20giant%20tortoise%2C%20head%20profile%20%28Chelonoidis%20niger%20hoodensis%29.jpg?width=900",
    lat: -0.9538,
    lng: -90.9656,
  },
  {
    id: "machu-picchu-peru",
    name: "Machu Picchu",
    country: "Peru",
    countryCode: "PE",
    continent: "south-america",
    themes: ["culture", "adventure"],
    tags: ["popular"],
    blurb: "An Incan citadel perched on a cloud-wrapped ridge, reached via storied Andean trekking routes.",
    highlights: ["Sun Gate sunrise", "Inca Trail trek", "Huayna Picchu climb", "Sacred Valley"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Peru%20Machu%20Picchu%20Sunrise.jpg?width=900",
    lat: -13.1631,
    lng: -72.545,
  },
  {
    id: "rio-de-janeiro-brazil",
    name: "Rio de Janeiro",
    country: "Brazil",
    countryCode: "BR",
    continent: "south-america",
    themes: ["beach", "city"],
    tags: ["popular"],
    blurb: "Christ the Redeemer watches over Copacabana's sands, samba rhythms, and granite peaks tumbling to the sea.",
    highlights: ["Christ the Redeemer", "Copacabana Beach", "Sugarloaf Mountain", "Santa Teresa"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Christ%20the%20Redeemer%20-%20Cristo%20Redentor.jpg?width=900",
    lat: -22.9068,
    lng: -43.1729,
  },
  {
    id: "buenos-aires-argentina",
    name: "Buenos Aires",
    country: "Argentina",
    countryCode: "AR",
    continent: "south-america",
    themes: ["city", "culture"],
    tags: ["trending"],
    blurb: "Tango spills onto cobbled streets in a European-flavored capital built for late dinners and steakhouses.",
    highlights: ["Caminito street art", "tango show in San Telmo", "Recoleta Cemetery", "asado dinner"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/El%20caminito2%20-%20Buenos%20Aires%20-%20Argentina.jpg?width=900",
    lat: -34.6037,
    lng: -58.3816,
  },
  {
    id: "maasai-mara-kenya",
    name: "Maasai Mara",
    country: "Kenya",
    countryCode: "KE",
    continent: "africa",
    themes: ["wildlife", "nature"],
    tags: ["popular"],
    blurb: "Endless savanna hosts the Great Migration and dense prides of lions across Kenya's most famous reserve.",
    highlights: ["Great Migration river crossings", "big-cat game drives", "hot-air balloon safari", "Maasai village visit"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Southern%20African%20lion%20in%20Maasai%20Mara%2C%20Kenya.jpg?width=900",
    lat: -1.5,
    lng: 35.15,
  },
  {
    id: "serengeti-tanzania",
    name: "Serengeti",
    country: "Tanzania",
    countryCode: "TZ",
    continent: "africa",
    themes: ["wildlife", "nature"],
    tags: ["popular"],
    blurb: "Millions of wildebeest sweep across endless plains in one of Africa's greatest wildlife spectacles.",
    highlights: ["Wildebeest migration", "Ngorongoro Crater day trip", "big-five game drives", "sunset over the plains"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Wildebeest%20Migration%20in%20Serengeti%20National%20Park%2C%20Tanzania.jpg?width=900",
    lat: -2.3333,
    lng: 34.8333,
  },
  {
    id: "marrakech-morocco",
    name: "Marrakech",
    country: "Morocco",
    countryCode: "MA",
    continent: "africa",
    themes: ["culture", "city"],
    tags: ["popular"],
    blurb: "Snake charmers and spice stalls fill a maze of souks beneath the Atlas Mountains' red-walled medina.",
    highlights: ["Jemaa el-Fnaa square", "souks of the medina", "Bahia Palace", "Majorelle Garden"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Jemaa%20el-Fnaa%20at%20night.jpg?width=900",
    lat: 31.6295,
    lng: -7.9811,
  },
  {
    id: "cape-town-south-africa",
    name: "Cape Town",
    country: "South Africa",
    countryCode: "ZA",
    continent: "africa",
    themes: ["city", "nature"],
    tags: ["trending"],
    blurb: "A flat-topped mountain looms over vineyards, penguin beaches, and one of the world's most dramatic coastlines.",
    highlights: ["Table Mountain cable car", "Cape of Good Hope", "Boulders Beach penguins", "Winelands day trip"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Table%20Mountain%20from%20Blouberg%20beach.jpg?width=900",
    lat: -33.9249,
    lng: 18.4241,
  },
  {
    id: "zanzibar-tanzania",
    name: "Zanzibar",
    country: "Tanzania",
    countryCode: "TZ",
    continent: "africa",
    themes: ["beach", "culture"],
    tags: ["trending"],
    blurb: "Spice-scented Stone Town gives way to powder-white beaches and turquoise water along the Swahili coast.",
    highlights: ["Stone Town alleys", "spice farm tour", "Nungwi beaches", "sunset dhow cruise"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Zanzibar%20beach.jpg?width=900",
    lat: -6.1659,
    lng: 39.2026,
  },
  {
    id: "cairo-egypt",
    name: "Cairo",
    country: "Egypt",
    countryCode: "EG",
    continent: "africa",
    themes: ["culture", "adventure"],
    tags: ["popular"],
    blurb: "The last standing Ancient Wonder rises at the edge of the city, beside millennia of pharaonic treasure.",
    highlights: ["Pyramids of Giza", "Sphinx", "Egyptian Museum", "Nile felucca ride"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Kheops-Pyramid.jpg?width=900",
    lat: 30.0444,
    lng: 31.2357,
  },
  {
    id: "sossusvlei-namibia",
    name: "Sossusvlei",
    country: "Namibia",
    countryCode: "NA",
    continent: "africa",
    themes: ["nature", "adventure"],
    tags: ["underRadar"],
    blurb: "Towering red sand dunes surround a bone-white clay pan dotted with centuries-old dead trees.",
    highlights: ["Dune 45 sunrise climb", "Deadvlei photography", "Sesriem Canyon", "stargazing in the Namib"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Sossusvlei%20Dune%20Rippled%20cropped.jpg?width=900",
    lat: -24.7333,
    lng: 15.4,
  },
  {
    id: "queenstown-new-zealand",
    name: "Queenstown",
    country: "New Zealand",
    countryCode: "NZ",
    continent: "oceania",
    themes: ["adventure", "nature"],
    tags: ["popular"],
    blurb: "The adventure capital of the world sits on an alpine lake ringed by the jagged Remarkables range.",
    highlights: ["Bungy jumping", "Milford Sound day trip", "Lake Wakatipu cruise", "Skyline gondola"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Queenstown%20NZ%2008.jpg?width=900",
    lat: -45.0312,
    lng: 168.6626,
  },
  {
    id: "sydney-australia",
    name: "Sydney",
    country: "Australia",
    countryCode: "AU",
    continent: "oceania",
    themes: ["city", "beach"],
    tags: ["popular"],
    blurb: "A sail-shaped opera house anchors a harbor city stitched together by beaches, ferries, and coastal walks.",
    highlights: ["Sydney Opera House", "Harbour Bridge climb", "Bondi to Coogee coastal walk", "Bondi Beach"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Sydney%20Opera%20House%20-%20Dec%202008.jpg?width=900",
    lat: -33.8688,
    lng: 151.2093,
  },
  {
    id: "fiji",
    name: "Fiji",
    country: "Fiji",
    countryCode: "FJ",
    continent: "oceania",
    themes: ["beach", "nature"],
    tags: ["trending"],
    blurb: "Warm South Pacific water, coral reefs, and castaway islands make Fiji a byword for barefoot luxury.",
    highlights: ["Mamanuca island-hopping", "snorkeling coral reefs", "kava ceremony", "Sabeto hot springs"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Sunset%20on%20the%20beach%20Fiji.jpg?width=900",
    lat: -17.7134,
    lng: 178.065,
  },
  {
    id: "tasmania-australia",
    name: "Tasmania",
    country: "Australia",
    countryCode: "AU",
    continent: "oceania",
    themes: ["nature", "wildlife"],
    tags: ["underRadar"],
    blurb: "Ancient rainforests, jagged dolerite peaks, and Tasmanian devils fill this wild island south of the mainland.",
    highlights: ["Cradle Mountain", "Wineglass Bay", "MONA museum", "Bruny Island wildlife"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Boat%20shed%20and%20Cradle%20Mountain%20at%20Dove%20Lake%2C%20Tas.jpg?width=900",
    lat: -42.8821,
    lng: 147.3272,
  },
  {
    id: "bora-bora-french-polynesia",
    name: "Bora Bora",
    country: "French Polynesia",
    countryCode: "PF",
    continent: "oceania",
    themes: ["beach", "nature"],
    tags: ["popular"],
    blurb: "An extinct volcano rises from a lagoon so blue it's become shorthand for the perfect honeymoon.",
    highlights: ["Overwater bungalows", "Mount Otemanu views", "lagoon snorkeling with rays", "sunset cruise"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Bora-Bora%20Lagoon%20-%20French%20Polynesia.jpg?width=900",
    lat: -16.5004,
    lng: -151.7415,
  },
  {
    id: "lyon-france",
    name: "Lyon",
    country: "France",
    countryCode: "FR",
    continent: "europe",
    themes: ["food", "culture"],
    tags: ["underRadar"],
    blurb: "France's food capital hides Renaissance passageways and bouchon bistros along the Rhône and Saône.",
    highlights: ["Vieux Lyon traboules", "bouchon dining", "Fourvière Basilica", "Les Halles de Lyon market"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Lyon%20-%20Vieux%20Lyon%206692.jpg?width=900",
    lat: 45.764,
    lng: 4.8357,
  },
  {
    id: "bologna-italy",
    name: "Bologna",
    country: "Italy",
    countryCode: "IT",
    continent: "europe",
    themes: ["food", "culture"],
    tags: ["underRadar"],
    blurb: "Porticoed medieval streets shelter Italy's culinary capital, home of ragù, tortellini, and centuries-old markets.",
    highlights: ["Piazza Maggiore", "Quadrilatero food market", "climbing the Asinelli Tower", "tortellini-making class"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Bologna%20-%20Piazza%20Maggiore%20from%20Palazzo%20Comunale.jpg?width=900",
    lat: 44.4949,
    lng: 11.3426,
  },
  {
    id: "kruger-south-africa",
    name: "Kruger National Park",
    country: "South Africa",
    countryCode: "ZA",
    continent: "africa",
    themes: ["wildlife", "nature"],
    tags: ["popular"],
    blurb: "One of Africa's largest game reserves delivers reliable big-five sightings across open bushveld.",
    highlights: ["Big-five game drives", "sunrise safari", "guided bush walks", "riverside hides"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Elephant%20Kruger%202003.jpg?width=900",
    lat: -24.011,
    lng: 31.4849,
  },
  {
    id: "okavango-delta-botswana",
    name: "Okavango Delta",
    country: "Botswana",
    countryCode: "BW",
    continent: "africa",
    themes: ["wildlife", "nature"],
    tags: ["underRadar"],
    blurb: "A vast inland river delta floods the Kalahari, moving safaris from Land Cruisers onto silent mokoro canoes.",
    highlights: ["Mokoro canoe safari", "elephant and lechwe sightings", "island bush walks", "birdwatching"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Delta%20del%20Okavango%2C%20Botsuana%2C%202018-07-31%2C%20DD%2001.jpg?width=900",
    lat: -19.2833,
    lng: 22.8833,
  },
  {
    id: "pantanal-brazil",
    name: "Pantanal",
    country: "Brazil",
    countryCode: "BR",
    continent: "south-america",
    themes: ["wildlife", "nature"],
    tags: ["underRadar"],
    blurb: "The world's largest tropical wetland packs in more jaguar sightings than anywhere else on Earth.",
    highlights: ["Jaguar-spotting river safaris", "caiman-filled wetlands", "hyacinth macaws", "horseback ranch stays"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Jaguar%20in%20Pantanal%20Brazil%201%20%28cropped%29.jpg?width=900",
    lat: -17.0,
    lng: -57.0,
  },
  {
    id: "hoi-an-vietnam",
    name: "Hoi An",
    country: "Vietnam",
    countryCode: "VN",
    continent: "asia",
    themes: ["food", "culture"],
    tags: ["trending"],
    blurb: "Silk lanterns light a preserved trading-port old town famous for tailors, lantern festivals, and street food.",
    highlights: ["Ancient Town lantern festival", "tailor-made suits", "Japanese Covered Bridge", "street-food tour"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Lanterns%20in%20Hoi%20An%2C%20Vietnam%20%2825708206924%29.jpg?width=900",
    lat: 15.8801,
    lng: 108.338,
  },
  {
    id: "chiang-mai-thailand",
    name: "Chiang Mai",
    country: "Thailand",
    countryCode: "TH",
    continent: "asia",
    themes: ["food", "culture"],
    tags: ["trending"],
    blurb: "Hundreds of temples and a walled old city sit beside a thriving night-market and cooking-school scene.",
    highlights: ["Doi Suthep temple", "Sunday walking street market", "Thai cooking class", "ethical elephant sanctuary"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/20171105%20Wat%20Chedi%20Luang%20Chiang%20Mai%209897%20DxO.jpg?width=900",
    lat: 18.7883,
    lng: 98.9853,
  },
  {
    id: "naples-italy",
    name: "Naples",
    country: "Italy",
    countryCode: "IT",
    continent: "europe",
    themes: ["food", "city"],
    tags: ["trending"],
    blurb: "The birthplace of pizza sprawls beneath Vesuvius, all chaotic energy, baroque churches, and Pompeii nearby.",
    highlights: ["Neapolitan pizza", "Pompeii day trip", "Naples Underground", "Spaccanapoli street"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/The%20harbor%20of%20Naples%20and%20Vesuvius%20at%20dawn.%20Italy.jpg?width=900",
    lat: 40.8518,
    lng: 14.2681,
  },
  {
    id: "uluru-australia",
    name: "Uluru",
    country: "Australia",
    countryCode: "AU",
    continent: "oceania",
    themes: ["nature", "culture"],
    tags: ["underRadar"],
    blurb: "A monolithic red sandstone rock sacred to the Anangu people glows crimson at sunrise and sunset over the outback.",
    highlights: ["Uluru base walk", "sunset viewing area", "Kata Tjuta domes", "Field of Light installation"],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Petermann%20Ranges%20%28AU%29%2C%20Uluru-Kata%20Tjuta%20National%20Park%2C%20Uluru%2C%20Kuniya%20Walk%20--%202019%20--%203651.jpg?width=900",
    lat: -25.3444,
    lng: 131.0369,
  },
];
